apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatur-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chatur-api-server
  strategy:
    rollingUpdate:
      maxSurge: 200%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chatur-api-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - chatur-api-server
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      containers:
        - name: controller
          image: harbor.cyverse.org/ai/fastchat:latest
          args:
            - "python3.9"
            - "-m"
            - "fastchat.serve.openai_api_server"
            - "--controller-address"
            - "http://chatur-controller"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
          ports:
            - name: listen-port
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chatur-api-server
spec:
  selector:
    app.kubernetes.io/name: chatur-api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
